[project]
name = "trendrop"
requires-python = "~=3.12"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "requests",
    "python-dotenv",
    "supabase",
    "slowapi",
    "pydantic",
    "email-validator",
    "python-multipart",
    "schedule",
    "resend",
    "numpy",
    "google-generativeai",
    "apify-client",
    "psycopg2-binary",
    "razorpay",
    "redis",
    "rq"
]
