-- Migration: Add spotify_feed_cache table for caching Spotify Viral feed items
CREATE TABLE IF NOT EXISTS public.spotify_feed_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trend_id BIGINT,
    audio_id TEXT,
    audio_title TEXT NOT NULL,
    audio_artist TEXT NOT NULL,
    spotify_id TEXT,
    popularity INT,
    score_basis TEXT,
    release_date TEXT,
    rank INT,
    data_source TEXT NOT NULL DEFAULT 'ig_trends_seeded',
    prediction JSONB,
    built_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS and restrict access to service_role only (prevents public anon key leak)
ALTER TABLE public.spotify_feed_cache ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to spotify_feed_cache" ON public.spotify_feed_cache;
DROP POLICY IF EXISTS "Service role full access on spotify_feed_cache" ON public.spotify_feed_cache;

CREATE POLICY "Service role full access on spotify_feed_cache"
    ON public.spotify_feed_cache
    FOR ALL
    USING (auth.role() = 'service_role');

-- Add trend_created_at column to support accurate 24h delay gating for Free tier
ALTER TABLE public.spotify_feed_cache ADD COLUMN IF NOT EXISTS trend_created_at TIMESTAMPTZ;

-- Add index on built_at and trend_created_at for fast cache freshness & gating lookup
CREATE INDEX IF NOT EXISTS idx_spotify_feed_cache_built_at ON public.spotify_feed_cache (built_at DESC);
CREATE INDEX IF NOT EXISTS idx_spotify_feed_cache_trend_created_at ON public.spotify_feed_cache (trend_created_at DESC);
