/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DataRightsRouteImport } from './routes/data-rights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as TrendIdRouteImport } from './routes/trend.$id'
import { Route as DealsNewRouteImport } from './routes/deals.new'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRightsRoute = DataRightsRouteImport.update({
  id: '/data-rights',
  path: '/data-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendIdRoute = TrendIdRouteImport.update({
  id: '/trend/$id',
  path: '/trend/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsNewRoute = DealsNewRouteImport.update({
  id: '/deals/new',
  path: '/deals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-rights': typeof DataRightsRoute
  '/generate': typeof GenerateRoute
  '/ideas': typeof IdeasRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/deals/new': typeof DealsNewRoute
  '/trend/$id': typeof TrendIdRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-rights': typeof DataRightsRoute
  '/generate': typeof GenerateRoute
  '/ideas': typeof IdeasRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/deals/new': typeof DealsNewRoute
  '/trend/$id': typeof TrendIdRoute
  '/deals': typeof DealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-rights': typeof DataRightsRoute
  '/generate': typeof GenerateRoute
  '/ideas': typeof IdeasRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/deals/new': typeof DealsNewRoute
  '/trend/$id': typeof TrendIdRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-rights'
    | '/generate'
    | '/ideas'
    | '/marketplace'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/studio'
    | '/terms'
    | '/admin/analytics'
    | '/deals/new'
    | '/trend/$id'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-rights'
    | '/generate'
    | '/ideas'
    | '/marketplace'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/studio'
    | '/terms'
    | '/admin/analytics'
    | '/deals/new'
    | '/trend/$id'
    | '/deals'
  id:
    | '__root__'
    | '/'
    | '/data-rights'
    | '/generate'
    | '/ideas'
    | '/marketplace'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/studio'
    | '/terms'
    | '/admin/analytics'
    | '/deals/new'
    | '/trend/$id'
    | '/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRightsRoute: typeof DataRightsRoute
  GenerateRoute: typeof GenerateRoute
  IdeasRoute: typeof IdeasRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  DealsNewRoute: typeof DealsNewRoute
  TrendIdRoute: typeof TrendIdRoute
  DealsIndexRoute: typeof DealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-rights': {
      id: '/data-rights'
      path: '/data-rights'
      fullPath: '/data-rights'
      preLoaderRoute: typeof DataRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend/$id': {
      id: '/trend/$id'
      path: '/trend/$id'
      fullPath: '/trend/$id'
      preLoaderRoute: typeof TrendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/new': {
      id: '/deals/new'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof DealsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRightsRoute: DataRightsRoute,
  GenerateRoute: GenerateRoute,
  IdeasRoute: IdeasRoute,
  MarketplaceRoute: MarketplaceRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  DealsNewRoute: DealsNewRoute,
  TrendIdRoute: TrendIdRoute,
  DealsIndexRoute: DealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
