/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DataRightsRouteImport } from './routes/data-rights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as TrendIdRouteImport } from './routes/trend.$id'
import { Route as DealsNewRouteImport } from './routes/deals.new'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRightsRoute = DataRightsRouteImport.update({
  id: '/data-rights',
  path: '/data-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendIdRoute = TrendIdRouteImport.update({
  id: '/trend/$id',
  path: '/trend/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsNewRoute = DealsNewRouteImport.update({
  id: '/deals/new',
  path: '/deals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-rights': typeof DataRightsRoute
  '/generate': typeof GenerateRoute
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/users': typeof AdminUsersRoute
  '/deals/new': typeof DealsNewRoute
  '/trend/$id': typeof TrendIdRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-rights': typeof DataRightsRoute
  '/generate': typeof GenerateRoute
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/users': typeof AdminUsersRoute
  '/deals/new': typeof DealsNewRoute
  '/trend/$id': typeof TrendIdRoute
  '/deals': typeof DealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/data-rights': typeof DataRightsRoute
  '/generate': typeof GenerateRoute
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/stats': typeof StatsRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/users': typeof AdminUsersRoute
  '/deals/new': typeof DealsNewRoute
  '/trend/$id': typeof TrendIdRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/data-rights'
    | '/generate'
    | '/ideas'
    | '/login'
    | '/marketplace'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/studio'
    | '/terms'
    | '/admin/analytics'
    | '/admin/plans'
    | '/admin/users'
    | '/deals/new'
    | '/trend/$id'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/data-rights'
    | '/generate'
    | '/ideas'
    | '/login'
    | '/marketplace'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/studio'
    | '/terms'
    | '/admin/analytics'
    | '/admin/plans'
    | '/admin/users'
    | '/deals/new'
    | '/trend/$id'
    | '/deals'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/data-rights'
    | '/generate'
    | '/ideas'
    | '/login'
    | '/marketplace'
    | '/privacy'
    | '/settings'
    | '/signup'
    | '/stats'
    | '/studio'
    | '/terms'
    | '/admin/analytics'
    | '/admin/plans'
    | '/admin/users'
    | '/deals/new'
    | '/trend/$id'
    | '/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DataRightsRoute: typeof DataRightsRoute
  GenerateRoute: typeof GenerateRoute
  IdeasRoute: typeof IdeasRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StatsRoute: typeof StatsRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DealsNewRoute: typeof DealsNewRoute
  TrendIdRoute: typeof TrendIdRoute
  DealsIndexRoute: typeof DealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-rights': {
      id: '/data-rights'
      path: '/data-rights'
      fullPath: '/data-rights'
      preLoaderRoute: typeof DataRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend/$id': {
      id: '/trend/$id'
      path: '/trend/$id'
      fullPath: '/trend/$id'
      preLoaderRoute: typeof TrendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/new': {
      id: '/deals/new'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof DealsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DataRightsRoute: DataRightsRoute,
  GenerateRoute: GenerateRoute,
  IdeasRoute: IdeasRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StatsRoute: StatsRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminUsersRoute: AdminUsersRoute,
  DealsNewRoute: DealsNewRoute,
  TrendIdRoute: TrendIdRoute,
  DealsIndexRoute: DealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
